package mid

// The aim of the first stage is to implement a Domain-specific language,but have some differences.
//
// The code generated by midlang is highly customizable. Use templates to generate code, even documents.
// midlang was committed to eradicating boring and tedious code which can be generated, not just as a data interchange format.
// The compiler midc compile midlang source code to an AST, and then you can visit the AST in template file.
//
// https://midlang.org/#whats-midlang
